name: JS build files

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string
      dir:
        required: true
        type: string

jobs:

  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'

      - name: 'Check changed files'
        id: 'changed-files'
        uses: tj-actions/changed-files@v23.1
        with:
          fetch-depth: 2
          files: |
            src/**

      - name: 'Cache node_modules'
        if: steps.changed-files.outputs.any_changed == 'true'
        id: 'modules-cache'
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: 'Run npm install'
        if: |
          steps.modules-cache.outputs.cache-hit != 'true' &&
          steps.changed-files.outputs.any_changed == 'true'
        run: npm install

      - name: 'Run npm build'
        if: steps.changed-files.outputs.any_changed == 'true'
        run: npm run build

      - name: 'Commit build changes'
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: ${{ inputs.message }}
          add: ${{ inputs.dir }}
