name: 'JS CI'

on:
  workflow_call:

jobs:

  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: 'Check changed files'
        id: 'changed-files'
        uses: tj-actions/changed-files@v34
        with:
          files: |
            src/**

      - name: 'Cache node_modules'
        if: steps.changed-files.outputs.any_changed == 'true'
        id: 'modules-cache'
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: 'Run npm install'
        if: |
          steps.modules-cache.outputs.cache-hit != 'true' &&
          steps.changed-files.outputs.any_changed == 'true'
        run: npm install

      - name: 'Run npm run lint:js'
        if: steps.changed-files.outputs.any_changed == 'true'
        run: npm run lint:js

      - name: 'Run npm test'
        if: steps.changed-files.outputs.any_changed == 'true'
        run: npm test
