name: 'Main action'

on:
  workflow_dispatch:

jobs:

  js:
    uses: tomusborne/edge22-actions/.github/workflows/js-ci.yml@v1

  php:
    uses: tomusborne/edge22-actions/.github/workflows/php-ci.yml@v1

  build:
    uses: tomusborne/edge22-actions/.github/workflows/js-build.yml@v1
    needs: js
    with:
      message: 'Update dist files'
      dir: 'dist/'
