name: 'Main action'

on:
  workflow_dispatch:

jobs:

  js:
    uses: ./.github/workflows/js-ci.yml

  php:
    uses: ./.github/workflows/php-ci.yml

  build:
    uses: ./.github/workflows/js-build.yml
    needs: js
    with:
      message: 'Update dist files'
      dir: 'dist/'
