name: 'Main action'

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  release-check:
    if: ${{ contains(github.event.pull_request.title, 'Release:') }}
    uses: tomusborne/edge22-actions/.github/workflows/release-check.yml@main

  js:
    uses: tomusborne/edge22-actions/.github/workflows/js-ci.yml@main

  php:
    uses: tomusborne/edge22-actions/.github/workflows/php-ci.yml@main

  build:
    uses: tomusborne/edge22-actions/.github/workflows/js-build.yml@main
    needs: js
    with:
      message: 'Update dist files'
      dir: 'dist/'
