name: 'PHP CI'

on:
  workflow_call:

jobs:

  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 'Validate composer'
        run: composer validate --strict

      - name: 'Cache vendor'
        id: 'vendor-cache'
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-modules-${{ hashFiles('**/composer.lock') }}

      - name: 'Run composer install'
        if: steps.vendor-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress

      - name: 'Run composer run-script lint'
        run: composer run-script lint

      - name: 'Run composer run-script test'
        run: composer run-script test
