name: 'Release check'

on:
  workflow_dispatch:
    inputs:
      pr-title:
        required: true
        default: 'Release: 1.0.1'
        description: 'Test'
        type: string

jobs:

  check-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: export NEXT_VERSION=${PR_TITLE:9}
        env:
          PR_TITLE: ${{ inputs.pr-title }}
      - run: 'git show README.md | grep -wq "+Stable tags: $NEXT_VERSION" | exit "$?"'

# ${{ github.event.pull_request.title }}
