name: 'Release check'

on:
  pull_request:
    branches:
      - main

jobs:

  check-version:
    name: 'Check versions'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 'Check README.md version'
        run: 'cat README.md | grep -w "Stable tag: ${PR_TITLE:9}"'
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}

      - name: 'Check package.json version'
        run: 'cat package.json | grep -w "\"version\": \"${PR_TITLE:9}\","'
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}

      - name: 'Check plugin header version'
        run: 'cat plugin.php | grep -w " * Version: ${PR_TITLE:9}"'
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}

      - name: 'Check PHP constant version'
        run: "cat plugin.php | grep -w \"define( 'GENERATEBLOCKS_VERSION', '${PR_TITLE:9}' );\""
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
