name: 'Release check'

on:
  pull_request:
    branches:
      - master

  workflow_dispatch:
    inputs:
      pr-title:
        required: true
        default: 'Release: 1.0.1'
        description: 'Test'
        type: string

jobs:

  check-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 'Check README.md version'
        run: 'cat README.md | grep -w "Stable tag: ${PR_TITLE:9}"'
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}

      - name: 'Check package.json version'
        run: 'cat package.json | grep -w "\"version\": \"${PR_TITLE:9}\","'
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
